/*
    This is a file containing the namespace for the Syiro Audio Player and Video Player, as well as shared player functionality.
    The Audio Player is exposed via syiro.audioplayer.
    The Video Player is exposed via syiro.videoplayer.
    The shared Player functionality is exposed via syiro.player.
*/

/// <reference path="component.ts" />
/// <reference path="events.ts" />
/// <reference path="interfaces.ts" />
/// <reference path="mediaplayer.ts" />
/// <reference path="utilities.ts" />

// #region Shared Player Functionality
// DEPRECATION NOTE: Deprecation in 1.9 cycle

namespace syiro.player {

	export var New = syiro.mediaplayer.New;
	export var Generate = syiro.mediaplayer.New;

	export var DurationChange = syiro.mediaplayer.DurationChange;
	export var FetchInnerContentElement = syiro.mediaplayer.FetchInnerContentElement;
	export var FetchSources = syiro.mediaplayer.FetchSources;
	export var GenerateSources = syiro.mediaplayer.GenerateSources;
	export var GetPlayerLengthInfo = syiro.mediaplayer.GetPlayerLengthInfo;
	export var IsPlaying = syiro.mediaplayer.IsPlaying;
	export var IsPlayable = syiro.mediaplayer.IsPlayable;
	export var IsStreamable = syiro.mediaplayer.IsStreamable;
	export var PlayOrPause = syiro.mediaplayer.PlayOrPause;
	export var Reset = syiro.mediaplayer.Reset;
	export var SetSources = syiro.mediaplayer.SetSources;
	export var SetTime = syiro.mediaplayer.SetTime;
	export var SetVolume = syiro.mediaplayer.SetVolume;
	export var ToggleFullscreen = syiro.mediaplayer.ToggleFullscreen;
	export var ToggleMenuDialog = syiro.mediaplayer.ToggleMenuDialog;

}

// #endregion

// #region Syiro Player Controls Component
// DEPRECATION NOTE: Deprecation in 1.9 cycle

namespace syiro.playercontrol {

	export var New = syiro.mediacontrol.New;
	export var Generate = syiro.mediacontrol.New;

	export var ShowVolumeSlider = syiro.mediacontrol.ShowVolumeSlider;
	export var TimeLabelUpdater = syiro.mediacontrol.TimeLabelUpdater;
	export var Toggle = syiro.mediacontrol.Toggle;
}

// #region Audio Player Component
// DEPRECATION NOTE: Deprecation in 1.9 cycle

namespace syiro.audioplayer {

    // #region Audio Player Generator

    export function New(properties : Object) : ComponentObject { // Generate a Audio Player Component and return a Component Object
        properties["type"] = "audio"; // Set Media Player type to audio
		return syiro.mediaplayer.New(properties); // Return the ComponentObject generated by the Media Player New() func
    }

	// #endregion

	export var CenterInformation = syiro.mediaplayer.CenterInformation;
}

// #endregion

// #region Video Player Component
// DEPRECATION NOTE: Deprecation in 1.9 cycle

namespace syiro.videoplayer {

    // #region Video Player Generator

    export function New(properties : Object) : ComponentObject { // Generate a Video Player Component and return a Component Object
		properties["type"] = "video"; // Set Media Player type to audio
        return syiro.mediaplayer.New(properties); // Call to generate a new video-type (default) Media Player
    }

    // #endregion

}

// #endregion
