/// <reference path="syiro.d.ts" />
/// <reference path="perfily.d.ts" />

function RunBenchmarks(){

	// #region Syiro Init Benchmark

	var syiroInitPerfilyInstance = new Perfily({ // Create a Perfily instance for initialization of Syiro
		"name" : "Syiro Init",
		"function" : function(){
			syiro.Init();
		}
	});

	syiroInitPerfilyInstance.Run(); // Run syiroInitPerfilyInstance

	// #endregion

	// #region Syiro ElementCreator Benchmark

	var generatedSyiroElement; // Define generatedSyiroElement as the element generated by the ElementCreator

	var syiroElementCreatorPerfilyInstance = new Perfily({ // Create a Perfily instance for ElementCreator in Syiro
		"name" : "Syiro ElementCreator",
		"function" : function(){
			generatedSyiroElement = syiro.utilities.ElementCreator("p", { "content" : "Example paragraph" });
		}
	});

	syiroElementCreatorPerfilyInstance.Run(); // Run syiroElementCreatorPerfilyInstance

	// #endregion

	// #region Syiro SecondsToTimeFormat Benchmark

	var timeValidObject = syiro.utilities.SecondsToTimeFormat(4523); // Create a "valid" time Object to use with the Perfily instance

	var syiroSecondsToTimeFormatPerfilyInstance = new Perfily({ // Create a Perfily instance for Syiro's SecondsToTimeFormat
		"name" : "Syiro SecondsToTimeFormat",
		"expecting" : JSON.stringify(timeValidObject), // Compare the JSON of timeValidObject with that provided by SecondsToTimeFormat
		"function" : function(){
			var localTimeObject = syiro.utilities.SecondsToTimeFormat(4523);
			return JSON.stringify(localTimeObject);
		}
	})

	syiroSecondsToTimeFormatPerfilyInstance.Run(); // Run syiroSecondsToTimeFormatPerfilyInstance

	// #endregion

	// #region Syiro Add() Benchmark

	var syiroAddPerfilyInstance = new Perfily({ // Create a Perfily instance for adding a component or Element via Syiro
		"name" : "Syiro Add",
		"function" : function(){
			syiro.component.Add("append", document.body, generatedSyiroElement);
		}
	});

	syiroAddPerfilyInstance.Run(); // Run syiroAddPerfilyInstance

	// #endregion

	// #region Syiro Remove() Benchmark

	var syiroRemovePerfilyInstance = new Perfily({ // Create a Perfily instance for removing a component or Element via Syiro
		"name" : "Syiro Remove",
		"function" : function(){
			syiro.component.Remove(generatedSyiroElement);
		}
	});

	syiroRemovePerfilyInstance.Run(); // Run syiroRemovePerfilyInstance

	// #endregion

	BenchmarkComponents(); // Generate and Benchmark Components
}

function BenchmarkComponents(){
	// #region Syiro New Basic Button Benchmark

	var syiroGeneratedBasicButton;

	var syiroNewBasicButtonPerfilyInstance = new Perfily({ // Create a Perfily instance for creating a new Basic Button
		"name" : "Syiro New Basic Button",
		"function" : function(){
			syiroGeneratedBasicButton = syiro.button.New({"type" : "basic", "content" : "Basic Button"});
		}
	});

	syiroNewBasicButtonPerfilyInstance.Run(); // Run syiroNewBasicButtonPerfilyInstance

	// #endregion

	// #region Syiro New Toggle Button Benchmark

	var syiroNewToggleButtonPerfilyInstance = new Perfily({ // Create a Perfily instance for creating a new Toggle Button
		"name" : "Syiro New Toggle Button",
		"function" : function(){
			syiro.button.New({"type" : "toggle", "default" : true});
		}
	});

	syiroNewToggleButtonPerfilyInstance.Run(); // Run syiroNewToggleButtonPerfilyInstance

	// #endregion

	// #region Syiro New Toggle Button Benchmark

	var syiroButtongroupPerfilyInstance = new Perfily({ // Create a Perfily instance for creating a new Buttongroup
		"name" : "Syiro New Buttongroup",
		"function" : function(){
			syiro.buttongroup.New({
				"items" : [ syiroGeneratedBasicButton, { "content" : "Button2" }, { "content" : "Button3" } ],
				"active" : 2
			});
		}
	});

	syiroButtongroupPerfilyInstance.Run(); // Run syiroButtongroupPerfilyInstance

	// #endregion

	// #region Syiro New List Item Benchmark

	var syiroGeneratedListItem;

	var syiroListItemPerfilyInstance = new Perfily({ // Create a Perfily instance for creating a new List Item
		"name" : "Syiro New List Item",
		"function" : function(){
			syiroGeneratedListItem = syiro.listitem.New({ "label" : "List Item" });
		}
	});

	syiroListItemPerfilyInstance.Run(); // Run syiroListItemPerfilyInstance

	// #endregion

	// #region Syiro New List Benchmark

	var syiroGeneratedList;

	var syiroListPerfilyInstance = new Perfily({ // Create a Perfily instance for creating a new List
		"name" : "Syiro New List",
		"function" : function(){
			syiroGeneratedList = syiro.list.New({ "items" : [syiroGeneratedListItem] });
		}
	});

	syiroListPerfilyInstance.Run(); // Run syiroListPerfilyInstance

	// #endregion

	// #region Syiro New Navbar Benchmark

	var syiroNavbarPerfilyInstance = new Perfily({ // Create a Perfily instance for creating a new Navbar
		"name" : "Syiro New Navbar",
		"function" : function(){
			syiro.navbar.New({ "items" : [{ "link" : "http://syiro.com", "title" : "Syiro"}], "position" : "fixed" });
		}
	});

	syiroNavbarPerfilyInstance.Run(); // Run syiroNavbarPerfilyInstance

	// #endregion

	// #region Syiro New Searchbox Benchmark

	var syiroSearchboxPerfilyInstance = new Perfily({ // Create a Perfily instance for creating a new Searchbox
		"name" : "Syiro New Searchbox",
		"function" : function(){
			syiro.searchbox.New({ "content" : "Type your things..." });
		}
	});

	syiroSearchboxPerfilyInstance.Run(); // Run syiroSearchboxPerfilyInstance

	// #endregion

	// #region Syiro New Sidepane Benchmark

	var syiroSidepanePerfilyInstance = new Perfily({ // Create a Perfily instance for creating a new Sidepane
		"name" : "Syiro New Sidepane",
		"function" : function(){
			syiro.sidepane.New({ "header" : "Sidepane Header", "items" : [ syiroGeneratedList ] });
		}
	});

	syiroSidepanePerfilyInstance.Run(); // Run syiroSearchboxPerfilyInstance

	// #endregion

	// #region Syiro New Toast Benchmark

	var syiroToastPerfilyInstance = new Perfily({ // Create a Perfily instance for creating a new Toast
		"name" : "Syiro New Toast",
		"function" : function(){
			syiro.toast.New({ "type" : "normal", "title" : "This is a Toast!", "message" : "This is a message!" });
		}
	});

	syiroToastPerfilyInstance.Run(); // Run syiroToastPerfilyInstance

	// #endregion
}

function TestPlayerFunctionality(){

}