/// <reference path="syiro.d.ts" />
/// <reference path="perfily.d.ts" />

var perfilyInstance = new Perfily({ "autoclearExpecting" : true, "autorun" : true } ); // Create a new Perfily Instance with autoclearExpecting set to true and autorunning after SetFunction

// #region Global Variables

var generatedSyiroElement; // Define generatedSyiroElement as the element generated by the ElementCreator
var timeValidObject = syiro.utilities.SecondsToTimeFormat(4523); // Create a "valid" time Object to use with the Perfily instance
var syiroGeneratedAudioPlayer;
var syiroGeneratedBasicButton;
var syiroGeneratedToggleButton;
var syiroGeneratedButtongroup;
var syiroGeneratedList;
var syiroGeneratedListItem;
var syiroGeneratedNavbar;
var syiroGeneratedSearchbox;
var syiroGeneratedToast;
var syiroGeneratedVideoPlayer;

// #endregion

function RunBenchmarks(){

	// #region Syiro Init Benchmark

	perfilyInstance.SetName("Init");
	perfilyInstance.SetFunction(function(){ // Set function to call syiro.Init()
		syiro.Init();
	});

	// #endregion

	// #region Syiro ElementCreator Benchmark

	perfilyInstance.SetName("ElementCreator");
	perfilyInstance.SetFunction(function(){ // Set function to generate Element
		generatedSyiroElement = syiro.utilities.ElementCreator("p", { "content" : "Example paragraph" });
	});

	// #endregion

	// #region Syiro SecondsToTimeFormat Benchmark

	perfilyInstance.SetName("SecondsToTimeFormat");
	perfilyInstance.SetExpecting(JSON.stringify(timeValidObject)); // Compare the JSON of timeValidObject with that provided by SecondsToTimeFormat
	perfilyInstance.SetFunction( function(){
		var localTimeObject = syiro.utilities.SecondsToTimeFormat(4523);
		return JSON.stringify(localTimeObject);
	});

	// #endregion

	// #region Syiro Add() Benchmark

	perfilyInstance.SetName("Add");
	perfilyInstance.SetFunction(function(){
		syiro.component.Add("append", document.body, generatedSyiroElement); // Add a component or Element via Syiro
	});

	// #endregion

	// #region Syiro Remove() Benchmark

	perfilyInstance.SetName("Remove");
	perfilyInstance.SetFunction(function(){
		syiro.component.Remove(generatedSyiroElement); // Remove a component or Element via Syiro
	});

	// #endregion

	TestButtongroupAndButtons(); // Run the benchmarking of Buttongroup and Buttons
	TestListAndListItem(); // Run the benchmarking of List and List Items
	TestMediaPlayers(); // Run the benchmarking of the Media Players
	TestNavbar(); // Run the benchmarking of Navbar
	TestSearchbox(); // Run the benchmarking of Searchbox
	TestSidepane(); // Run the benchmarking of Sidepane
	TestToast(); // Run the benchmarking of Toast
}

// #region Buttongroup and Buttons Testing

function TestButtongroupAndButtons(){
	console.log("----- Buttongroup and Buttons Testing -----");

	// #region Syiro New Basic Button Benchmark

	perfilyInstance.SetName("New Basic Button");
	perfilyInstance.SetFunction( function(){
		syiroGeneratedBasicButton = syiro.button.New({"type" : "basic", "content" : "Basic Button"});
	});

	// #endregion

	// #region Syiro New Toggle Button Benchmark

	perfilyInstance.SetName("New Toggle Button");
	perfilyInstance.SetFunction(function(){
		syiroGeneratedToggleButton = syiro.button.New({"type" : "toggle", "default" : true});
	});

	// #endregion

	// #region Syiro New Buttongroup Benchmark

	perfilyInstance.SetName("New Buttongroup");
	perfilyInstance.SetFunction(function(){
		syiroGeneratedButtongroup = syiro.buttongroup.New({
			"items" : [ syiroGeneratedBasicButton, { "content" : "Button2" }, { "content" : "Button3" } ],
			"active" : 2
		});
	});

	// #endregion

	// #region Syiro Basic Button Function Benchmarking

	perfilyInstance.SetName("Button SetIcon");
	perfilyInstance.SetFunction(function(){
		syiro.button.SetIcon(syiroGeneratedBasicButton, "img/message-inverted.png");
	});

	perfilyInstance.SetName("Button SetImage");
	perfilyInstance.SetFunction(function(){
		syiro.button.SetImage(syiroGeneratedBasicButton, "img/message-inverted.png");
	});

	perfilyInstance.SetName("Button SetText");
	perfilyInstance.SetFunction(function(){
		syiro.button.SetText(syiroGeneratedBasicButton, "Text");
	});

	// #endregion

	// #region Syiro Toggle Button Function Benchmarking

	perfilyInstance.SetName("Toggle Button - Toggle Function");
	perfilyInstance.SetFunction(function(){
		syiro.button.Toggle(syiroGeneratedToggleButton);
	});

	// #endregion

	// #region Syiro Buttongroup Function Benchmarking

	perfilyInstance.SetName("Buttongroup Toggle");
	perfilyInstance.SetFunction(function(){
		syiro.buttongroup.Toggle(syiroGeneratedBasicButton);
	});

	// #endregion
}

// #endregion

// #region List and List Item Testing

function TestListAndListItem(){
	console.log("----- List and List Item Testing -----");

	// #region Syiro New List Item Benchmark

	perfilyInstance.SetName("New List Item");
	perfilyInstance.SetFunction(function(){
		syiroGeneratedListItem = syiro.listitem.New({ "label" : "List Item" });
	});

	// #endregion

	// #region Syiro New List Benchmark

	perfilyInstance.SetName("New List");
	perfilyInstance.SetFunction(function(){
		syiroGeneratedList = syiro.list.New({ "items" : [syiroGeneratedListItem] });
	});

	// #endregion

	perfilyInstance.SetName("List SetHeader");
	perfilyInstance.SetFunction(function(){
		syiro.list.SetHeader(syiroGeneratedList, "Header");
	});

	perfilyInstance.SetName("List Item SetControl");
	perfilyInstance.SetFunction(function(){
		syiro.listitem.SetControl(syiroGeneratedListItem, syiroGeneratedToggleButton);
	});

	perfilyInstance.SetName("List Item SetImage");
	perfilyInstance.SetFunction(function(){
		syiro.listitem.SetImage(syiroGeneratedListItem, "img/google-plus.png");
	});

	perfilyInstance.SetName("List Item SetLabel");
	perfilyInstance.SetFunction(function(){
		syiro.listitem.SetLabel(syiroGeneratedListItem, "Updated Label");
	});

	perfilyInstance.SetName("List Item SetLink");
	perfilyInstance.SetFunction(function(){
		syiro.listitem.SetLink(syiroGeneratedListItem, { "link" : "http://syiro.com", "title" : "Syiro" });
	});

}

// #endregion

// #region Media Players Testing

function TestMediaPlayers(){
	console.log("----- Media Players Testing -----");

	// #region Syiro New Audio Player Benchmark

	perfilyInstance.SetName("New Audio Player");
	perfilyInstance.SetFunction(function(){
		syiroGeneratedAudioPlayer = syiro.audioplayer.New(
		{
			"sources": ["http://upload.wikimedia.org/wikipedia/commons/c/c8/Example.ogg", "http://www.noiseaddicts.com/samples/55.mp3" ],
			"art" : "https://c2.staticflickr.com/6/5134/5518988345_9df9892bb2_b.jpg",
			"title" : "Example OGG File",
			"artist" : "JesseW"
		}
    	);
	});

	// #endregion

	// #region Syiro New Video Player Benchmark

	perfilyInstance.SetName("New Video Player");
	perfilyInstance.SetFunction(function(){
		syiroGeneratedVideoPlayer = syiro.videoplayer.New(
			{
				"art" : "img/video-art.png",
				"height" : 200,
				"width" : (200 * (16 / 9)),
				"sources" : ["http://download.blender.org/peach/trailer/trailer_480p.mov", "http://mirror.cessen.com/blender.org/peach/trailer/trailer_iphone.m4v", "http://video.webmfiles.org/big-buck-bunny_trailer.webm"]
			}
    	);
	});

	syiro.component.Add("append", syiro.page, syiroGeneratedVideoPlayer); // Add the video player to the DOM

	perfilyInstance.SetName("Media Player FetchInnerContentElement");
	perfilyInstance.SetFunction(function(){
		syiro.player.FetchInnerContentElement(syiroGeneratedVideoPlayer);
	});

	perfilyInstance.SetName("Media Player FetchSources");
	perfilyInstance.SetFunction(function(){
		syiro.player.FetchSources(syiroGeneratedVideoPlayer);
	});

	perfilyInstance.SetName("Media Player IsPlayable");
	perfilyInstance.SetExpecting(true); // Expect to be playable
	perfilyInstance.SetFunction(function(){
		syiro.player.IsPlayable(syiroGeneratedVideoPlayer);
	});

	perfilyInstance.SetName("Media Player IsPlaying");
	perfilyInstance.SetExpecting(false); // Expect to be not playing
	perfilyInstance.SetFunction(function(){
		syiro.player.IsPlaying(syiroGeneratedVideoPlayer);
	});

	perfilyInstance.SetName("Media Player IsStreamable");
	perfilyInstance.SetExpecting(false); // Expect to be not streamable
	perfilyInstance.SetFunction(function(){
		syiro.player.IsStreamable(syiroGeneratedVideoPlayer);
	});

	perfilyInstance.SetName("Media Player PlayOrPause");
	perfilyInstance.SetFunction(function(){
		syiro.player.PlayOrPause(syiroGeneratedVideoPlayer);
	});

	perfilyInstance.SetName("Media Player SetTime");
	perfilyInstance.SetFunction(function(){
		syiro.player.SetTime(syiroGeneratedVideoPlayer, 7);
	});

	perfilyInstance.SetName("Media Player SetVolume");
	perfilyInstance.SetFunction(function(){
		syiro.player.SetVolume(syiroGeneratedVideoPlayer, 0.5);
	});

	perfilyInstance.SetName("Media Player Reset");
	perfilyInstance.SetFunction(function(){
		syiro.player.Reset(syiroGeneratedVideoPlayer);
	});

}

// #endregion

// #region Navbar Testing

function TestNavbar(){
	console.log("----- Navbar Testing -----");

	// #region Syiro New Navbar Benchmark

	perfilyInstance.SetName("New Navbar");
	perfilyInstance.SetFunction(function(){
		syiro.navbar.New({ "items" : [{ "link" : "http://syiro.com", "title" : "Syiro"}], "position" : "fixed" });
	});

	// #endregion

	perfilyInstance.SetName("Navbar AddLink");
	perfilyInstance.SetFunction(function(){
		syiro.navbar.AddLink("append",  syiroGeneratedNavbar, { "link" : "http://syiro.com", "title" : "Syiro"} );
	});

	perfilyInstance.SetName("Navbar RemoveLink");
	perfilyInstance.SetFunction(function(){
		syiro.navbar.RemoveLink(syiroGeneratedNavbar, { "link" : "http://syiro.com", "title" : "Syiro"} );
	});

	perfilyInstance.SetName("Navbar SetLabel");
	perfilyInstance.SetFunction(function(){
		syiro.navbar.SetLabel(syiroGeneratedNavbar, "Label");
	});

	perfilyInstance.SetName("Navbar SetLogo");
	perfilyInstance.SetFunction(function(){
		syiro.navbar.SetLogo(syiroGeneratedNavbar, "img/facebook.png");
	});

}

// #endregion

// #region Searchbox Testing

function TestSearchbox(){
	console.log("----- Searchbox Testing -----");

	// #region Syiro New Searchbox Benchmark

	perfilyInstance.SetName("New Searchbox");
	perfilyInstance.SetFunction(function(){
		syiroGeneratedSearchbox = syiro.searchbox.New({ "content" : "Type your things..." });
	});

	// #endregion

	perfilyInstance.SetName("Searchbox SetText");
	perfilyInstance.SetFunction(function(){
		syiro.searchbox.SetText(syiroGeneratedSearchbox, "Test");
	});
}

// #endregion

// #region Sidepane Testing

function TestSidepane(){
	console.log("----- Sidepane Testing -----");

	// #region Syiro New Sidepane Benchmark

	perfilyInstance.SetName("New Sidepane");
	perfilyInstance.SetFunction(function(){
		syiro.sidepane.New({ "header" : "Sidepane Header", "items" : [ syiroGeneratedList ] });
	});

	// #endregion
}

// #endregion

// #region Toast Testing

function TestToast(){
	console.log("----- Toast Testing -----");

	// #region Syiro New Toast Benchmark

	perfilyInstance.SetName("New Toast");
	perfilyInstance.SetFunction(function(){
		syiroGeneratedToast = syiro.toast.New({ "type" : "normal", "title" : "This is a Toast!", "message" : "This is a message!" });
	});

	// #endregion

	syiro.component.Add("append", document.body, syiroGeneratedToast); // Append for Toggle Testing

	perfilyInstance.SetName("Toast Toggle");
	perfilyInstance.SetFunction(function(){
		syiro.toast.Toggle(syiroGeneratedToast);
	});

	perfilyInstance.SetName("Toast Clear");
	perfilyInstance.SetFunction(function(){
		syiro.toast.Clear(syiroGeneratedToast);
	});
}