#!/bin/bash

hook(){
	printf "Post-Compiling Hook:\n"

#	allJSFiles=$(find -name "*.js") # Get all Javascript files recursively

#	for file in $allJSFiles; do
#		if [[ "$file" != *.min.js ]]; then # If it is not a minified Javascript file, then remove it
#			fileNameWithoutPathRemnant="${file#./}" # Remove the ./ from the directory
#
#			echo "Removing $fileNameWithoutPathRemnant"
#			rm -f "$fileNameWithoutPathRemnant"
#
#		fi
#	done

	allCSSFiles=$(find -name "*.css") # Get all CSS files recursively

	for file in $allCSSFiles; do
		if [[ "$file" != *.min.css ]]; then # If it is not a minified CSS file
			fileNameWithoutPathRemnant="${file#./}" # Remove the ./ from the directory
			fileNameWithoutExtension=${fileNameWithoutPathRemnant%%.css}
			fileChanged=false #Set fileChanged to false by default.

			echo "-----$fileNameWithoutPathRemnant------"

			fileChanged $fileNameWithoutPathRemnant

			if [ $FILE_CHANGED == "CHANGED" ]; then # If the file has been changed (or no sum exists)
				echo "We have detected that this is either a new file or has been changed. Saving the sha1sum."
				echo "$cleanShaSum" > "$fileNameWithoutPathRemnant.sha1sum"

				echo "Compressing file."
				curl -X POST -s --data-urlencode "input@$fileNameWithoutPathRemnant" http://cssminifier.com/raw > "$fileNameWithoutExtension.min.css"
			else
				echo "We have detected no changes. Will not change sha1sum or compress."
			fi

			printf "\n"
		fi
	done
}
